[tool.framework]
include = [
    "framework",
]

pythonVersion = "3.6"

typeCheckingMode = "strict"

reportImportCycles = false

reportPrivateUsage = false

# enable these for now as none of raise any
# errors anyway
reportCallInDefaultInitializer = true
reportImplicitStringConcatenation = true
